SYSTARG=MacOSX
OBJTYPE=arm64
<../../mkconfig
SYSTARG=MacOSX
OBJTYPE=arm64

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=

# GUI Backend Selection
# Options: headless, sdl3
# Default: headless (no display, terminal only)
GUIBACK=headless

INSTALLDIR=/sys/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

<| sh ../port/mkdevlist < $CONF	#sets $IP, $DEVS, $PORT, $LIBS

# Include GUI backend configuration
<mkfile-gui-$GUIBACK

OBJ=\
	asm-$OBJTYPE.$O\
	os.$O\
	$GUISRC\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

HFILES=\

CFLAGS=\
	'''-DROOT="'.'"'''\
	-DEMU -I. -I../port\
	-I../../$SYSTARG/$OBJTYPE/include\
	-I../../include\
	-I../../libinterp\
	$CTHREADFLAGS $CFLAGS $EMUOPTIONS $GUIFLAGS\

KERNDATE=0

SYSLIBS= \
	-lm\
	-lpthread\
	-framework CoreFoundation\
	-framework IOKit\

default:V:	$O.$CONF


$O.$CONF:	$OBJ $CONF.c $CONF.root.h # $LIBNAMES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS $GUILIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

# Explicit rule for asm-arm64.o to avoid macOS case-insensitive .s/.S ambiguity
asm-arm64.$O:	asm-arm64.s
	$AS $ASFLAGS asm-arm64.s

<../port/portmkfile

ipif.c:N:	../FreeBSD/ipif.c
devfs.c:N:	../port/devfs-posix.c
